version: '3.9'
services:

  database:
    image: postgres:12.3-alpine
    restart: always
    volumes:
      - /data/postgres /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: user
      POSTGRES_DB: database
    hostname: posthost
    ports:
      - "5432:5432"


  minio:
    hostname: minmin
    image: minio/minio
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: "key"
      MINIO_SECRET_KEY: "secreasdasdasdat"
    command: server --console-address :9001 /data

  backend:
    build: .
    ports:
      - '8000:80'

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"